In [1]:
import joblib

model_sla = joblib.load("../output/model_sla_rf_tfidf.pkl")

In [2]:
nouveau_ticket = {
    "Priorité": "Moyenne (P3)",
    "Categorie": "Gestion des comptes et mots de passe",
    "Titre de la demande": "Réinitialisation du mot de passe Windows"
}

In [3]:
import pandas as pd

ticket = pd.DataFrame([nouveau_ticket])

ticket

,Priorité,Categorie,Titre de la demande
0,Moyenne (P3),Gestion des comptes et mots de passe,Réinitialisation du mot de passe Windows

In [4]:
prediction = model_sla.predict(ticket)

prediction

array([1])

In [5]:
probabilite = model_sla.predict_proba(ticket)[0, 1]

probabilite

np.float64(0.6350681001765269)

In [6]:
print(f"Probabilité de dépassement SLA : {probabilite:.2%}")

Probabilité de dépassement SLA : 63.51%

In [7]:
def predire_sla(priorite, categorie, titre):
    
    ticket = pd.DataFrame([{
        "Priorité": priorite,
        "Categorie": categorie,
        "Titre de la demande": titre
    }])
    
    prediction = model_sla.predict(ticket)[0]
    probabilite = model_sla.predict_proba(ticket)[0, 1]
    
    if prediction == 1:
        resultat = "RISQUE DE DÉPASSEMENT SLA"
    else:
        resultat = "SLA PROBABLEMENT RESPECTÉ"
    
    return resultat, probabilite

In [8]:
resultat, probabilite = predire_sla(
    "Moyenne (P3)",
    "Gestion des comptes et mots de passe",
    "Réinitialisation du mot de passe Windows"
)

print(resultat)
print(f"Probabilité : {probabilite:.2%}")

RISQUE DE DÉPASSEMENT SLA
Probabilité : 63.51%

In [9]:
tickets_test = pd.DataFrame([
    {
        "Priorité": "Critique (P1)",
        "Categorie": "Securite informatique",
        "Titre de la demande": "Alerte sécurité poste de travail"
    },
    {
        "Priorité": "Faible (P4)",
        "Categorie": "Assistance & Demandes generales",
        "Titre de la demande": "Demande de service"
    },
    {
        "Priorité": "Moyenne (P3)",
        "Categorie": "SAP & Applications metier",
        "Titre de la demande": "Assistance SAP"
    }
])

tickets_test["Prediction_SLA"] = model_sla.predict(tickets_test)

tickets_test["Probabilite_depassement"] = (
    model_sla.predict_proba(tickets_test)[:, 1]
)

tickets_test

,Priorité,Categorie,Titre de la demande,Prediction_SLA,Probabilite_depassement
0,Critique (P1),Securite informatique,Alerte sécurité poste de travail,1,0.911328
1,Faible (P4),Assistance & Demandes generales,Demande de service,0,0.456472
2,Moyenne (P3),SAP & Applications metier,Assistance SAP,1,0.878170